name: Android

on:
  workflow_dispatch:
    inputs:
#       environment:
#         required: true
#         type: choice
#         description: Select build enviroment
#         default: Dev
#         options:
#           - Hyperspace
#           - Beta
#           - Dev
#           - Prod
#           - Staging
#           - Regression
#       unityVersion:
#          description: 'Select the Unity version'
#          required: true 
#          type: choice
#          default: 2021.3.13f1
#          options:
#           - 2020.3.11f1
#           - 2021.3.13f1
#           - 2022.1.21f1
      AltUnity:
         description: 'Use AltUnity library'
         required: true 
         type: boolean
#       TestingBuild:
#          description: 'Testing build'
#          required: true 
#          type: boolean

jobs:
  buildForAndroidPlatform:
    name: Build Android App
    runs-on: [self-hosted, Unity]
    env:
      BUILD_NUMBER_FILE_PATH: ${{ format('{0}/Client/Assets/Resources/buildNumber.txt', github.workspace) }}
#       ANDROID_UPLOAD_KEYSTORE_NAME: "aab.keystore"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          submodules: "recursive"
          token: ${{ secrets.GIT_ACCESSTOKEN_CICD }}

      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
         token: ${{secrets.github_token}} 
            
      - name: Manual QA
        if: ${{ contains(github.ref, 'master') || contains(github.ref, 'release/') }}
        run: |
            echo "Manual QA build"
            echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}" >> $GITHUB_ENV 
      - name: automation branch
        if: ${{ inputs.AltUnity }}
        run: |
            echo "automation build"
            echo "BUILD_NUMBER=800${{ env.BUILD_NUMBER }}" >> $GITHUB_ENV         
#       - name: feature branch
#         if: ${{ contains(github.ref, 'feature/') && !inputs.TestingBuild && !inputs.AltUnity }}
#         run: |
#             echo "feature build"
#             echo "BUILD_NUMBER=900${{ env.BUILD_NUMBER }}" >> $env:GITHUB_ENV 
#       - name: testing 
#         if: ${{ contains(github.ref, 'task/') ||  inputs.TestingBuild }}
#         run: |
#             echo "testing build"
#             echo "BUILD_NUMBER=700${{ env.BUILD_NUMBER }}" >> $env:GITHUB_ENV 
                       
      - name: Print new build number
        run: echo "Build number is ${{ env.BUILD_NUMBER }}" 
