name: Automerge

on:
 push:
     branches:
       - release/*

# env:
#   MY_REPO: https://github_username:${{secrets.GITHUB_TOKEN}}@github.com/mydevopsgithub/merge
#   MY_BRANCH: master
#   MASTER_REPO: https://github.com/mydevopsgithub/merge
# #   MASTER_BRANCH: github.ref 


jobs:
  merge:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
     with:
       ref: 'master'
#    - name: get the branch
#      run: |
#          echo "MASTER_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
       
   - name: Merge release branch to default branch
     run: |
       for branch in $(git for-each-ref --format='%(refname:short)' 'ref/heads/release/*');do
        git merge --no-ff --no-commit $branch
        done
   - name: Send Email on merge Conflict
     env:
       EMAIL_RECIPIENT: 'neelimamaddela95@gmail.com'
     run: |
        if git merge --no-commit --no-ff $(git for-each-ref --format='%(refname:short)' 'ref/heads/release/*') | grep -q 'CONFLICT'; then
          echo "Merge Conflicts Detected" | mail -s "Merge Conflicts Detected" $EMAIL_RECIPIENT
          git merge --abort
        else
          git merge --continue
        fi
        
   - name: Push changes 
     uses: ad-m/github-push-action@master
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}

  

       
   
