name: Automerge

on:
 push:
     branches:
       - 'release/*'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Merge changes from release branches
        run: |
          for branch in $(git branch --remote --list "origin/release/*" --not merged); do
          git fetch origin $branch
          fit merge --no-ff $barnch -m "Auto-merge release barnch"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Check for merge conflicts 
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "merge conflict detected"
            echo "$(git status)"
            echo "Conflict detected in the release branch merge to default branch." | mail -s "Merge conflict detected" neelimamaddela95@gmail.com
            exit 1
            fi
            
      - name: Push changes to default branch
        run: |
           git config --global user.name "Neelima"
           git config --global user.email "neelimamaddela95@gmail.com"
           git commit -m "initial commit"
           git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  send-email:
    needs: [auto-merge]
    runs-on: ubuntu-latest
    
    steps:
      - name: Send email notification
        uses: jakejarvis/send-email-action@master
        with:
          server_address: smtp.gamil.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Merge conflict detected 
          body: "Conflicts detected in the release branch to deafult branch"
          to: neelimamaddela95@gmail.com

        
