name: Automerge

on:
 push:
     branches:
       - release/*

env:
  MY_REPO: https://github_username:${{secrets.GITHUB_TOKEN}}@github.com/mydevopsgithub/merge
  MY_BRANCH: master
  MASTER_REPO: https://github.com/mydevopsgithub/merge
#   MASTER_BRANCH: github.ref 


jobs:
  merge:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: grt the branch
     run: |
         $MASTER_BRANCH=(git rev-parse --abbrev-ref HEAD)            
         echo $MASTER_BRANCH   
         "MASTER_BRANCH=$MASTER_BRANCH" >> $env:GITHUB_ENV 
       
   - name: Merge release branch to default branch
     run: |
       git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
       cd tmp
       git config user.name "mydevopsgithub"
       git config user.email "neelimamaddela95@gmail.com"
       git config pull.rebase false
       git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
       git push
