name: Automerge

on:
 push:
     branches:
       - release/*

# env:
#   MY_REPO: https://github_username:${{secrets.GITHUB_TOKEN}}@github.com/mydevopsgithub/merge
#   MY_BRANCH: master
#   MASTER_REPO: https://github.com/mydevopsgithub/merge
# #   MASTER_BRANCH: github.ref 


jobs:
  merge:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
#    - name: grt the branch
#      run: |
#          echo "MASTER_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
       
   - name: Merge release branch to default branch
     run: git merge origin/release/*
   - name: Send Email on merge Conflict
     if: failure()
     run: |
       echo "There was a merge conflict in the ${GITHUB_REPOSITORY} repo.Please reeview the chnages and reslove any conflicts" | mail -s "Merge Conflicts Detected" neelimamaddela95@gmail.com

  

       
   
