name: Automerge

on:
   push:
     branches:
       - release/a.b.c


# env:
#   # replace "github_username" with your GitHub username
#   # replace "github.com/username/repo.git" with your GitHub repo path
#   # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
#   MY_REPO: https://github_username:${{secrets.GITHUB_TOKEN}}@github.com/mydevopsgithub/merge

#   # replace "long-lived_branch_name" with your branch name
#   MY_BRANCH: release/a.b.c

#   # replace it with the path to master repo
#   MASTER_REPO: https://github.com/mydevopsgithub/merge

#   # replace "master" with your master branch name
#   MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Merge release branch to default branch
      run: |
        git config user.name "mydevopsgithub"
        git config user.email "neelimamaddela95@gmail.com"
        git checkout master
        git merge --no-ff ${{ github.event.ref }}
        git push
