name: Automerge

on:
 push:
     branches:
       - 'release/*'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: action/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependenceies
        run: npm ci
      - name: Merge changes from release branches
        run: |
          git config --global user.name "Neelima"
          git config --global user.email "neelimamaddela95@gmail.com"
          git checkout main
          git merge --no-ff --no-edit rlease
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v3.1.1
        with:
          server_address: smtp.gamil.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Merge conflict detected 
          body: "Conflicts detected in the release branch to deafult branch"
          from: Neelima
          to: neelimamaddela95@gmail.com

        
