name: Automerge

on:
 push:
     branches:
       - 'release/*'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        
      - name: Auto-merge
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main'
              head: context.ref,
              title: 'merge ${context.ref} to default branch',
              maintainer_can_modify: true,
              draft: false
            })  
            
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo, 
              pull_number: pullRequest.number,
              commit_title: 'Merge ${context.ref} to default branch',
              merge_method: 'squash'
            })
          
        
      - name: Check for merge conflicts 
        run: |
          git fetch --all
          git checkout main
          git pull origin main
          
          if [ -n "$(git status --porcelain)" ]; then
            echo "merge conflict detected in default branch"
            echo "$(git status)"
            echo "Conflict detected in the default branch" | mail -s "Merge conflict detected" neelimamaddela95@gmail.com
            exit 1
          fi
          
          git checkout ${GITHUB_REF#refs/heads/}
          git pull orgin ${GITHUB_REF#refs/heads/}
          
          if [ -n "$(git status --porcelain)" ]; then
            echo "merge conflict detected in release branch"
            echo "$(git status)"
            echo "Conflict detected in the release branch" | mail -s "Merge conflict detected" neelimamaddela95@gmail.com
            exit 1
          fi
          
            
     
        
