name: Checkmarx SCA Scan

'on': 
    schedule:
      - cron: '0 0 * * 6' # Runs every week on Saturday
# on:
#   push:
#     branches: [CWP-4033-DEV-TASK---To-check-&-act-on-Checkmarx-workflow]

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.4 # GitHub Action version
      with:
       project: "CareAR merged app GitHub" #${{ secrets.CHECKMARX_PROJECT }}   # <-- Insert Checkmarx CxSCA Project Namee
       sca_api_url: https://api.scacheckmarx.com
       sca_app_url: https://sca.scacheckmarx.com
       sca_access_control_url: https://platform.checkmarx.net
       sca_tenant: "xeroxprod"  # <-- Insert Checkmarx CxSCA Tenant
       sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
       sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.
       break_build: false
       scanners: sca
       bug_tracker: Sarif
       params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --repo-url="https://github.com/H1991/dvwaHarsha" --cx-flow.filterSeverity --cx-flow.filterCategory
