name: Starter Workflow Demo
'on': 
 workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: demo workflow job
        run: echo This is a demo start workflow
        
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
        
      - name: Every time
        run: echo "This step will always run"
        
      - name: Run a one-line script
        run: echo Hello from  Organization ab
