name: Starter Workflow Demo
'on': 
 workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: demo workflow job
        run: echo This is a demo start workflow
        
      - name: Run a one-line script
        run: echo Hello from  Organization
